package com.github.dappermickie.runepouch.loadout.names;

import net.runelite.api.gameval.SpriteID;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class RunepouchLoadoutIcon {
  public int spriteId;
  public String name;

  public RunepouchLoadoutIcon(int spriteId, String name) {
    this.spriteId = spriteId;
    this.name = name;
  }

  public static List<RunepouchLoadoutIcon> getIcons(String search) {
    if (search.isEmpty()) {
      return ICONS;
    }

    return ICONS.stream()
      .filter(icon -> icon.name.toLowerCase().contains(search.toLowerCase()))
      .collect(Collectors.toList());
  }

  public static final List<RunepouchLoadoutIcon> ICONS = new ArrayList<RunepouchLoadoutIcon>() {
    {
      add(new RunepouchLoadoutIcon(SpriteID.AccManIcons._6, "Default"));

      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WIND_STRIKE, "Wind Strike"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CONFUSE, "Confuse"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WATER_STRIKE, "Water Strike"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_1_ENCHANT, "Lvl 1 Enchant"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.EARTH_STRIKE, "Earth Strike"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WEAKEN, "Weaken"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.FIRE_STRIKE, "Fire Strike"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.BONES_TO_BANANAS, "Bones to Bananas"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WIND_BOLT, "Wind Bolt"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CURSE, "Curse"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.LOW_LEVEL_ALCHEMY, "Low Level Alchemy"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WATER_BOLT, "Water Bolt"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.VARROCK_TELEPORT, "Varrock Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_2_ENCHANT, "Lvl 2 Enchant"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.EARTH_BOLT, "Earth Bolt"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.LUMBRIDGE_TELEPORT, "Lumbridge Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.TELEKINETIC_GRAB, "Telekinetic Grab"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.FIRE_BOLT, "Fire Bolt"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.FALADOR_TELEPORT, "Falador Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CRUMBLE_UNDEAD, "Crumble Undead"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WIND_BLAST, "Wind Blast"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.SUPERHEAT_ITEM, "Superheat Item"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CAMELOT_TELEPORT, "Camelot Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WATER_BLAST, "Water Blast"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_3_ENCHANT, "Lvl 3 Enchant"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.EARTH_BLAST, "Earth Blast"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.HIGH_LEVEL_ALCHEMY, "High Level Alchemy"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CHARGE_WATER_ORB, "Charge Water Orb"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_4_ENCHANT, "Lvl 4 Enchant"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.FIRE_BLAST, "Fire Blast"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CHARGE_EARTH_ORB, "Charge Earth Orb"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WIND_WAVE, "Wind Wave"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CHARGE_FIRE_ORB, "Charge Fire Orb"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WATER_WAVE, "Water Wave"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CHARGE_AIR_ORB, "Charge Air Orb"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_5_ENCHANT, "Lvl 5 Enchant"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.EARTH_WAVE, "Earth Wave"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.FIRE_WAVE, "Fire Wave"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.IBAN_BLAST, "Iban Blast"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.ARDOUGNE_TELEPORT, "Ardougne Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WATCHTOWER_TELEPORT, "Watchtower Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.VULNERABILITY, "Vulnerability"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.ENFEEBLE, "Enfeeble"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.STUN, "Stun"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.FLAMES_OF_ZAMORAK, "Flames of Zamorak"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CLAWS_OF_GUTHIX, "Claws of Guthix"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.SARADOMIN_STRIKE, "Saradomin Strike"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CALL_ANIMAL, "Call Animal"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.RAISE_SKELETON, "Raise Skeleton"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.SUMMON_DEMON, "Summon Demon"));

      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.BIND, "Bind"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SNARE, "Snare"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.ENTANGLE, "Entangle"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.CHARGE, "Charge"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TROLLHEIM_TELEPORT, "Trollheim Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.MAGIC_DART, "Magic Dart"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.ICE_RUSH, "Ice Rush"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.ICE_BURST, "Ice Burst"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.ICE_BLITZ, "Ice Blitz"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.ICE_BARRAGE, "Ice Barrage"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SMOKE_RUSH, "Smoke Rush"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SMOKE_BURST, "Smoke Burst"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SMOKE_BLITZ, "Smoke Blitz"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SMOKE_BARRAGE, "Smoke Barrage"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.BLOOD_RUSH, "Blood Rush"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.BLOOD_BURST, "Blood Burst"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.BLOOD_BLITZ, "Blood Blitz"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.BLOOD_BARRAGE, "Blood Barrage"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SHADOW_RUSH, "Shadow Rush"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SHADOW_BURST, "Shadow Burst"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SHADOW_BLITZ, "Shadow Blitz"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SHADOW_BARRAGE, "Shadow Barrage"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.PADDEWWA_TELEPORT, "Paddewwa Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SENNTISTEN_TELEPORT, "Senntisten Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.KHARYRLL_TELEPORT, "Kharyll Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.LASSAR_TELEPORT, "Lassar Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.DAREEYAK_TELEPORT, "Dareeyak Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.CARRALLANGAR_TELEPORT, "Carrallangar Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.ANNAKARL_TELEPORT, "Annakarl Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.GHORROCK_TELEPORT, "Ghorrock Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEOTHER_LUMBRIDGE, "Teleother Lumbridge"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEOTHER_FALADOR, "Teleother Falador"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEOTHER_CAMELOT, "Teleother Camelot"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELE_BLOCK, "Tele Block"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.LVL_6_ENCHANT, "Lvl 6 Enchant"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.BONES_TO_PEACHES, "Bones to Peaches"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_HOUSE, "Teleport to House"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.LUMBRIDGE_HOME_TELEPORT, "Lumbridge Home Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_APE_ATOLL, "Teleport to Ape Atoll"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.ENCHANT_CROSSBOW_BOLT, "Enchant Crossbow Bolt"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_BOUNTY_TARGET, "Teleport to Bounty Target"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_KOUREND, "Teleport to Kourend"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.LVL_7_ENCHANT, "Lvl 7 Enchant"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.WIND_SURGE, "Wind Surge"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.WATER_SURGE, "Water Surge"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.EARTH_SURGE, "Earth Surge"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.FIRE_SURGE, "Fire Surge"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.CIVITAS_ILLA_FORTIS_TELEPORT, "Civitas Ila Fortis Teleport"));

      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.BAKE_PIE, "Bake Pie"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.MOONCLAN_TELEPORT, "Moonclan Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.WATERBIRTH_TELEPORT, "Waterbirth Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.BOW_AND_ARROW, "Bow and Arrow"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.BARBARIAN_TELEPORT, "Barbarian Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.SUPERGLASS_MAKE, "Superglass Make"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.KHAZARD_TELEPORT, "Khazard Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.STRING_JEWELLERY, "String Jewellery"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.BOOST_POTION_SHARE, "Boost Potion Share"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.MAGIC_IMBUE, "Magic Imbue"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.FERTILE_SOIL, "Fertile Soil"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.STAT_RESTORE_POT_SHARE, "Stat Restore Pot Share"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.FISHING_GUILD_TELEPORT, "Fishing Guild Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CATHERBY_TELEPORT, "Catherby Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.ICE_PLATEAU_TELEPORT, "Ice Plateau Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.ENERGY_TRANSFER, "Energy Transfer"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_OTHER, "Cure Other"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.HEAL_OTHER, "Heal Other"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.VENGEANCE_OTHER, "Vengeance Other"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_ME, "Cure Me"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.GEOMANCY, "Geomancy"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.VENGEANCE, "Vengeance"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_GROUP, "Cure Group"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.HEAL_GROUP, "Heal Group"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_PLANT, "Cure Plant"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.NPC_CONTACT, "NPC Contact"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_MOONCLAN, "Tele Group Moonclan"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_WATERBIRTH, "Tele Group Waterbirth"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_BARBARIAN, "Tele Group Barbarian"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_KHAZARD, "Tele Group Khazard"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_FISHING_GUILD, "Tele Group Fishing Guild"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_CATHERBY, "Tele Group Catherby"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_ICE_PLATEAU, "Tele Group Ice Plateau"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.STAT_SPY, "Stat Spy"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.MONSTER_EXAMINE, "Monster Examine"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.HUMIDIFY, "Humidify"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.HUNTER_KIT, "Hunter Kit"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.DREAM, "Dream"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.PLANK_MAKE, "Plank Make"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.SPELLBOOK_SWAP, "Spellbook Swap"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TAN_LEATHER, "Tan Leather"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.RECHARGE_DRAGONSTONE, "Recharge Dragonstone"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.SPIN_FLAX, "Spin Flax"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.OURANIA_TELEPORT, "Ourania Teleport"));

      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_LESSER_GHOST, "Resurrect Lesser Ghost"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._24, "Resurrect Lesser Skeleton"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._25, "Resurrect Lesser Zombie"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._44, "Resurrect Superior Ghost (_44)"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_SUPERIOR_SKELETON, "Resurrect Superior Skeleton"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._48, "Resurrect Superior Zombie (_48)"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._45, "Resurrect Greater Ghost (_45)"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._47, "Resurrect Greater Skeleton (_47)"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_GREATER_ZOMBIE, "Resurrect Greater Zombie"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.ADEPT_REANIMATION, "Adept Reanimation"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.BASIC_REANIMATION, "Basic Reanimation"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.EXPERT_REANIMATION, "Expert Reanimation"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.MASTER_REANIMATION, "Master Reanimation"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.ARCEUUS_LIBRARY_TELEPORT, "Arceuus Library Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DRAYNOR_MANOR_TELEPORT, "Draynor Manor Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SALVE_GRAVEYARD_TELEPORT, "Salve Graveyard Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.MIND_ALTAR_TELEPORT, "Mind Altar Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESPAWN_TELEPORT, "Respawn Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.FENKENSTRAINS_CASTLE_TELEPORT, "Fenkenstrain's Castle Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.WEST_ARDOUGNE_TELEPORT, "West Ardougne Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.HARMONY_ISLAND_TELEPORT, "Harmony Island Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.BARROWS_TELEPORT, "Barrows Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.APE_ATOLL_TELEPORT, "Ape Atoll Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.CEMETERY_TELEPORT, "Cemetery Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_CROPS, "Resurrect Crops"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.GHOSTLY_GRASP, "Ghostly Grasp"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SKELETAL_GRASP, "Skeletal Grasp"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.UNDEAD_GRASP, "Undead Grasp"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.INFERIOR_DEMONBANE, "Inferior Demonbane"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SUPERIOR_DEMONBANE, "Superior Demonbane"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DARK_DEMONBANE, "Dark Demonbane"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.MARK_OF_DARKNESS, "Mark of Darkness"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.WARD_OF_ARCEUUS, "Ward of Arceuus"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.LESSER_CORRUPTION, "Lesser Corruption"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.GREATER_CORRUPTION, "Greater Corruption"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DEATH_CHARGE, "Death Charge"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DEMONIC_OFFERING, "Demonic Offering"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SINISTER_OFFERING, "Sinister Offering"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SHADOW_VEIL, "Shadow Veil"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DARK_LURE, "Dark Lure"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.VILE_VIGOUR, "Vile Vigour"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DEGRIME, "Degrime"));
      
      add(new RunepouchLoadoutIcon(SpriteID.SideIcons.MAGIC, "Spellbook Standard"));
      add(new RunepouchLoadoutIcon(SpriteID.SideIcons.SPELLBOOK_ANCIENT_MAGICKS, "Spellbook Ancient"));
      add(new RunepouchLoadoutIcon(SpriteID.SideIcons.SPELLBOOK_LUNAR, "Spellbook Lunar"));
      add(new RunepouchLoadoutIcon(SpriteID.SideIcons.SPELLBOOK_ARCEUUS, "Spellbook Arceuus"));
      
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.THICK_SKIN, "Thick Skin"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.BURST_OF_STRENGTH, "Burst of Strength"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.CLARITY_OF_THOUGHT, "Clarity of Thought"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.ROCK_SKIN, "Rock Skin"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.SUPERHUMAN_STRENGTH, "Superhuman Strength"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.IMPROVED_REFLEXES, "Improved Reflexes"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.RAPID_RESTORE, "Rapid Restore"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.RAPID_HEAL, "Rapid Heal"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_ITEM, "Protect Item"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.STEEL_SKIN, "Steel Skin"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.ULTIMATE_STRENGTH, "Ultimate Strength"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.INCREDIBLE_REFLEXES, "Incredible Reflexes"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_MAGIC, "Protect From Magic"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_MISSILES, "Protect From Missiles"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_MELEE, "Protect From Melee"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.REDEMPTION, "Redemption"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.RETRIBUTION, "Retribution"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.SMITE, "Smite"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.SHARP_EYE, "Sharp Eye"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.MYSTIC_WILL, "Mystic Will"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.HAWK_EYE, "Hawk Eye"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.MYSTIC_LORE, "Mystic Lore"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.EAGLE_EYE, "Eagle Eye"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.MYSTIC_MIGHT, "Mystic Might"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_SUMMONING, "Protect From Summoning"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.CHIVALRY, "Chivalry"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.PIETY, "Piety"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.PRESERVE, "Preserve"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.RIGOUR, "Rigour"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.AUGURY, "Augury"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.DEADEYE, "Deadeye"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.MYSTIC_VIGOUR, "Mystic Vigour"));

      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANCIENT_STRENGTH, "Ancient Strength"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANCIENT_SIGHT, "Ancient Sight"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANCIENT_WILL, "Ancient Will"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.TRINITAS, "Trinitas"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.DECIMATE, "Decimate"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANNIHILATE, "Annihilate"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.VAPORISE, "Vaporise"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.DAMPEN_MELEE, "Dampen Melee"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.DAMPEN_RANGED, "Dampen Ranged"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.DAMPEN_MAGIC, "Dampen Magic"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.PURGE, "Purge"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.REJUVENATION, "Rejuvenation"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.RUINOUS_GRACE, "Ruinous Grace"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.WRATH, "Wrath"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.METABOLISE, "Metabolise"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.BERSERKER, "Berserker"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.FUMUS_VOW, "Fumus Vow"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.CRUORS_VOW, "Cruors Vow"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.UMBRAS_VOW, "Umbras Vow"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.GLACIES_VOW, "Glacies Vow"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.INTENSIFY, "Intensify"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.REBUKE, "Rebuke"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.VINDICATION, "Vindication"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.PROTECT_ITEM, "Protect Item"));

      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ABYSSAL_SIRE, "Abyssal Sire"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ALCHEMICAL_HYDRA, "Alchemical Hydra"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.AMOXLIATL, "Amoxliatl"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_HUEYCOATL, "The Hueycoatl"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ROYAL_TITANS, "Royal Titans"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.YAMA, "Yama"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DOOM_OF_MOKHAIOTL, "Doom of Mokhaiotl"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.MIMIC, "Mimic"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.OBOR, "Obor"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ARAXXOR, "Araxxor"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.BRYOPHYTA, "Bryophyta"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.GIANT_MOLE, "Giant Mole"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.GROTESQUE_GUARDIANS, "Grotesque Guardians"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TEMPOROSS, "Tempoross"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.WINTERTODT, "Wintertodt"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.BARROWS_CHESTS, "Barrows Chests"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SARACHNIS, "Sarachnis"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KALPHITE_QUEEN, "Kalphite Queen"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.HESPORI, "Hespori"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SKOTIZO, "Skotizo"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ZALCANO, "Zalcano"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KING_BLACK_DRAGON, "King Black Dragon"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KRAKEN, "Kraken"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THERMONUCLEAR_SMOKE_DEVIL, "Thermonuclear Smoke Devil"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_GAUNTLET, "The Gauntlet"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ZULRAH, "Zulrah"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CERBERUS, "Cerberus"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.VORKATH, "Vorkath"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.GENERAL_GRAARDOR, "General Graardor"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KRIL_TSUTSAROTH, "Kril Tsutsaroth"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.COMMANDER_ZILYANA, "Commander Zilyana"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KREEARRA, "Kree'arra"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.NIGHTMARE, "Nightmare"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CORPOREAL_BEAST, "Corporeal Beast"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CHAMBERS_OF_XERIC, "Chambers of Xeric"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THEATRE_OF_BLOOD, "Theatre of Blood"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.NEX, "Nex"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DAGANNOTH_SUPREME, "Dagannoth Supreme"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DAGANNOTH_REX, "Dagannoth Rex"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DAGANNOTH_PRIME, "Dagannoth Prime"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_CORRUPTED_GAUNTLET, "The Corrupted Gauntlet"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CHAMBERS_OF_XERIC_CHALLENGE_MODE, "Chambers of Xeric Challenge Mode"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TOMBS_OF_AMASCUT, "Tombs of Amascut"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TOMBS_OF_AMASCUT_EXPERT, "Tombs of Amascut Expert"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.PHANTOM_MUSPAH, "Phantom Muspah"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CHAOS_ELEMENTAL, "Chaos Elemental"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ARTIO_CALLISTO, "Artio Callisto"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CALVARION_VETION, "Calvarion Vetion"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SPINDEL_VENENATIS, "Spinel Venenatis"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CHAOS_FANATIC, "Chaos Fanatic"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CRAZY_ARCHAEOLOGIST, "Crazy Archaeologist"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DERANGED_ARCHAEOLOGIST, "Deranged Archaeologist"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SCORPIA, "Scorpia"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TZTOK_JAD, "TzTok Jad"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TZKAL_ZUK, "TzKal Zuk"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_WHISPERER, "The Whisperer"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DUKE_SUCELLUS, "Duke Sucellus"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_LEVIATHAN, "The Leviathan"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.VARDORVIS, "Vardorvis"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SCURRIUS, "Scurrius"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SOL_HEREDIT, "Sol Heri"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.LUNAR_CHESTS, "Lunar Chests"));

      add(new RunepouchLoadoutIcon(SpriteID.Staticons.ATTACK, "Attack"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.STRENGTH, "Strength"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.DEFENCE, "Defence"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.RANGED, "Ranged"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.PRAYER, "Prayer"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.MAGIC, "Magic"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.HITPOINTS, "Hitpoints"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.AGILITY, "Agility"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.HERBLORE, "Herblore"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.THIEVING, "Thieving"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.CRAFTING, "Crafting"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.FLETCHING, "Fletching"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.MINING, "Mining"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.SMITHING, "Smithing"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.FISHING, "Fishing"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.COOKING, "Cooking"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.FIREMAKING, "Farming"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.WOODCUTTING, "Woodcutting"));
    }
  };
}

//       add(SpriteID.IconBoss25x25._0);
//       add(SpriteID.IconBoss25x25._1);
//       add(SpriteID.IconBoss25x25._2);
//       add(SpriteID.IconBoss25x25._3);
//       add(SpriteID.IconBoss25x25._4);
//       add(SpriteID.IconBoss25x25._5);
//       add(SpriteID.IconBoss25x25._6);
//       add(SpriteID.IconBoss25x25._7);
//       add(SpriteID.IconBoss25x25._8);
//       add(SpriteID.IconBoss25x25._9);
//       add(SpriteID.IconBoss25x25._10);
//       add(SpriteID.IconBoss25x25._11);
//       add(SpriteID.IconBoss25x25._12);
//       add(SpriteID.IconBoss25x25._13);
//       add(SpriteID.IconBoss25x25._14);
//       add(SpriteID.IconBoss25x25._15);
//       add(SpriteID.IconBoss25x25._16);
//       add(SpriteID.IconBoss25x25._17);
//       add(SpriteID.IconBoss25x25._18);
//       add(SpriteID.IconBoss25x25._19);
//       add(SpriteID.IconBoss25x25._20);
//       add(SpriteID.IconBoss25x25._21);
//       add(SpriteID.IconBoss25x25._22);
//       add(SpriteID.IconBoss25x25._23);
//       add(SpriteID.IconBoss25x25._24);
//       add(SpriteID.IconBoss25x25._25);
//       add(SpriteID.IconBoss25x25._26);
//       add(SpriteID.IconBoss25x25._27);
//       add(SpriteID.IconBoss25x25._28);
//       add(SpriteID.IconBoss25x25._29);
//       add(SpriteID.IconBoss25x25._30);
//       add(SpriteID.IconBoss25x25._31);
//       add(SpriteID.IconBoss25x25._32);
//       add(SpriteID.IconBoss25x25._33);
//       add(SpriteID.IconBoss25x25._34);
//       add(SpriteID.IconBoss25x25._35);
//       add(SpriteID.IconBoss25x25._36);
//       add(SpriteID.IconBoss25x25._37);
//       add(SpriteID.IconBoss25x25._38);
//       add(SpriteID.IconBoss25x25._39);
//       add(SpriteID.IconBoss25x25._40);
//       add(SpriteID.IconBoss25x25._41);
//       add(SpriteID.IconBoss25x25._42);
//       add(SpriteID.IconBoss25x25._43);
//       add(SpriteID.IconBoss25x25._44);
//       add(SpriteID.IconBoss25x25._45);
//       add(SpriteID.IconBoss25x25._46);
//       add(SpriteID.IconBoss25x25._47);
//       add(SpriteID.IconBoss25x25._48);
//       add(SpriteID.IconBoss25x25._49);
//       add(SpriteID.IconBoss25x25._50);
//       add(SpriteID.IconBoss25x25._51);
//       add(SpriteID.IconBoss25x25._52);
//       add(SpriteID.IconBoss25x25._53);
//       add(SpriteID.IconBoss25x25._54);
//       add(SpriteID.IconBoss25x25._55);
//       add(SpriteID.IconBoss25x25._56);
//       add(SpriteID.IconBoss25x25._57);
//       add(SpriteID.IconBoss25x25._58);
//       add(SpriteID.IconBoss25x25._59);
//       add(SpriteID.IconBoss25x25._60);
//       add(SpriteID.IconBoss25x25._61);
//       add(SpriteID.IconBoss25x25._62);
//       add(SpriteID.IconBoss25x25._63);
//       add(SpriteID.IconBoss25x25._64);

//       add(SpriteID.HiscoresBosses._0);
//       add(SpriteID.HiscoresBosses._1);
//       add(SpriteID.HiscoresBosses._2);
//       add(SpriteID.HiscoresBosses._3);
//       add(SpriteID.HiscoresBosses._4);
//       add(SpriteID.HiscoresBosses._5);
//       add(SpriteID.HiscoresBosses._6);
//       add(SpriteID.HiscoresBosses._7);
//       add(SpriteID.HiscoresBosses._8);
//       add(SpriteID.HiscoresBosses._9);
//       add(SpriteID.HiscoresBosses._10);
//       add(SpriteID.HiscoresBosses._11);
//       add(SpriteID.HiscoresBosses._12);
//       add(SpriteID.HiscoresBosses._13);
//       add(SpriteID.HiscoresBosses._14);
//       add(SpriteID.HiscoresBosses._15);
//       add(SpriteID.HiscoresBosses._16);
//       add(SpriteID.HiscoresBosses._17);
//       add(SpriteID.HiscoresBosses._18);
//       add(SpriteID.HiscoresBosses._19);
//       add(SpriteID.HiscoresBosses._20);
//       add(SpriteID.HiscoresBosses._21);
//       add(SpriteID.HiscoresBosses._22);
//       add(SpriteID.HiscoresBosses._23);
//       add(SpriteID.HiscoresBosses._24);
//       add(SpriteID.HiscoresBosses._25);
//       add(SpriteID.HiscoresBosses._26);
//       add(SpriteID.HiscoresBosses._27);
//       add(SpriteID.HiscoresBosses._28);
//       add(SpriteID.HiscoresBosses._29);
//       add(SpriteID.HiscoresBosses._30);
//       add(SpriteID.HiscoresBosses._31);
//       add(SpriteID.HiscoresBosses._32);
//       add(SpriteID.HiscoresBosses._33);
//       add(SpriteID.HiscoresBosses._34);
//       add(SpriteID.HiscoresBosses._35);
//       add(SpriteID.HiscoresBosses._36);
//       add(SpriteID.HiscoresBosses._37);
//       add(SpriteID.HiscoresBosses._38);
//       add(SpriteID.HiscoresBosses._39);
//       add(SpriteID.HiscoresBosses._40);
//       add(SpriteID.HiscoresBosses._41);
//       add(SpriteID.HiscoresBosses._42);
//       add(SpriteID.HiscoresBosses._43);
//       add(SpriteID.HiscoresBosses._44);
//       add(SpriteID.HiscoresBosses._45);
//       add(SpriteID.HiscoresBosses._46);
//       add(SpriteID.HiscoresBosses._47);
//       add(SpriteID.HiscoresBosses._48);

//       add(SpriteID.FrexRunes._0);
//       add(SpriteID.FrexRunes._1);
//       add(SpriteID.FrexRunes._2);
//       add(SpriteID.FrexRunes._3);
//       add(SpriteID.FrexRunes._4);
//       add(SpriteID.FrexRunes._5);

//       add(SpriteID.SideIcons.SPELLBOOK_ANCIENT_MAGICKS);
//       add(SpriteID.SideIcons.SPELLBOOK_LUNAR);
//       add(SpriteID.SideIcons.SPELLBOOK_ARCEUUS);

//       add(SpriteID.Staticons.ATTACK);
//       add(SpriteID.Staticons.STRENGTH);
//       add(SpriteID.Staticons.DEFENCE);
//       add(SpriteID.Staticons.RANGED);
//       add(SpriteID.Staticons.PRAYER);
//       add(SpriteID.Staticons.MAGIC);
//       add(SpriteID.Staticons.HITPOINTS);
//       add(SpriteID.Staticons.AGILITY);
//       add(SpriteID.Staticons.HERBLORE);
//       add(SpriteID.Staticons.THIEVING);
//       add(SpriteID.Staticons.CRAFTING);
//       add(SpriteID.Staticons.FLETCHING);
//       add(SpriteID.Staticons.MINING);
//       add(SpriteID.Staticons.SMITHING);
//       add(SpriteID.Staticons.FISHING);
//       add(SpriteID.Staticons.COOKING);
//       add(SpriteID.Staticons.FIREMAKING);
//       add(SpriteID.Staticons.WOODCUTTING);

//       add(SpriteID.Staticons2._0);
//       add(SpriteID.Staticons2._1);
//       add(SpriteID.Staticons2._2);
//       add(SpriteID.Staticons2._3);
//       add(SpriteID.Staticons2._4);
//       add(SpriteID.Staticons2._5);
//       add(SpriteID.Staticons2._6);
//       add(SpriteID.Staticons2._7);
//       add(SpriteID.Staticons2._8);
//       add(SpriteID.Staticons2._9);
//       add(SpriteID.Staticons2._10);
//       add(SpriteID.Staticons2._11);
//       add(SpriteID.Staticons2._12);

//       add(SpriteID.AccountIcons._0);
//       add(SpriteID.AccountIcons._1);
//       add(SpriteID.AccountIcons._2);
//       add(SpriteID.AccountIcons._3);
//       add(SpriteID.AccountIcons._4);

//       add(SpriteID.ToaInvocationIcons._0);
//       add(SpriteID.ToaInvocationIcons._1);
//       add(SpriteID.ToaInvocationIcons._2);
//       add(SpriteID.ToaInvocationIcons._3);
//       add(SpriteID.ToaInvocationIcons._4);
//       add(SpriteID.ToaInvocationIcons._5);
//       add(SpriteID.ToaInvocationIcons._6);
//       add(SpriteID.ToaInvocationIcons._7);
//       add(SpriteID.ToaInvocationIcons._8);
//       add(SpriteID.ToaInvocationIcons._9);
//       add(SpriteID.ToaInvocationIcons._10);
//       add(SpriteID.ToaInvocationIcons._11);
//       add(SpriteID.ToaInvocationIcons._12);
//       add(SpriteID.ToaInvocationIcons._13);
//       add(SpriteID.ToaInvocationIcons._14);
//       add(SpriteID.ToaInvocationIcons._15);
//       add(SpriteID.ToaInvocationIcons._16);
//       add(SpriteID.ToaInvocationIcons._17);
//       add(SpriteID.ToaInvocationIcons._18);
//       add(SpriteID.ToaInvocationIcons._19);
//       add(SpriteID.ToaInvocationIcons._20);
//       add(SpriteID.ToaInvocationIcons._21);
//       add(SpriteID.ToaInvocationIcons._22);
//       add(SpriteID.ToaInvocationIcons._23);

//       add(SpriteID.ToaDifficultyIcons._0);
//       add(SpriteID.ToaDifficultyIcons._1);
//       add(SpriteID.ToaDifficultyIcons._2);

//       add(SpriteID.HeadiconsPkInterface._0);
//       add(SpriteID.HeadiconsPkInterface._1);
//       add(SpriteID.HeadiconsPkInterface._2);
//       add(SpriteID.HeadiconsPkInterface._3);
//       add(SpriteID.HeadiconsPkInterface._7);
//       add(SpriteID.HeadiconsPkInterface._8);
//       add(SpriteID.HeadiconsPkInterface._9);
//       add(SpriteID.HeadiconsPkInterface._10);
//       add(SpriteID.HeadiconsPkInterface._11);
//       add(SpriteID.HeadiconsPkInterface._12);
//       add(SpriteID.HeadiconsPkInterface._14);
//       add(SpriteID.HeadiconsPkInterface._15);
//       add(SpriteID.HeadiconsPkInterface._16);
//       add(SpriteID.HeadiconsPkInterface._17);
//       add(SpriteID.HeadiconsPkInterface._18);
//       add(SpriteID.HeadiconsPkInterface._19);
//       add(SpriteID.HeadiconsPkInterface._21);
//       add(SpriteID.HeadiconsPkInterface._22);
//       add(SpriteID.HeadiconsPkInterface._23);
//       add(SpriteID.HeadiconsPkInterface._24);
//       add(SpriteID.HeadiconsPkInterface._25);
//       add(SpriteID.HeadiconsPkInterface._28);
//       add(SpriteID.HeadiconsPkInterface._29);
//       add(SpriteID.HeadiconsPkInterface._30);
//       add(SpriteID.HeadiconsPkInterface._31);
//       add(SpriteID.HeadiconsPkInterface._32);

//       add(SpriteID.IconYama34x34._0);
//       add(SpriteID.IconYama34x34._1);
//       add(SpriteID.IconYama34x34._2);
//       add(SpriteID.IconYama34x34._3);
//       add(SpriteID.IconYama34x34._4);

//       add(SpriteID.WintIcons._0);
//       add(SpriteID.WintIcons._1);
//       add(SpriteID.WintIcons._2);
//       add(SpriteID.WintIcons._3);
//       add(SpriteID.WintIcons.CRAFTING);
//       add(SpriteID.WintIcons.FIREMAKING_LOGS);
//       add(SpriteID.WintIcons.FIREMAKING);
//       add(SpriteID.WintIcons.MAGIC_RED);

//       add(SpriteID.SoulWarsStaticons._0);
//       add(SpriteID.SoulWarsStaticons._1);
//       add(SpriteID.SoulWarsStaticons._2);
//       add(SpriteID.SoulWarsStaticons._3);
//       add(SpriteID.SoulWarsStaticons._4);
//       add(SpriteID.SoulWarsStaticons._5);
//       add(SpriteID.SoulWarsStaticons._6);
//       add(SpriteID.SoulWarsStaticons._7);

//       add(SpriteID.IconAlchemyChemicals01_27x27._0);
//       add(SpriteID.IconAlchemyChemicals01_27x27._1);
//       add(SpriteID.IconAlchemyChemicals01_27x27._2);

//       add(SpriteID.Dt2Icons._0);
//       add(SpriteID.Dt2Icons._2);
//       add(SpriteID.Dt2Icons._4);
//       add(SpriteID.Dt2Icons._6);

//       add(SpriteID.ModIconsInterface._0);
//       add(SpriteID.ModIconsInterface._1);

//       add(SpriteID.ClanRankIcons._0);
//       add(SpriteID.ClanRankIcons._1);
//       add(SpriteID.ClanRankIcons._2);
//       add(SpriteID.ClanRankIcons._3);
//       add(SpriteID.ClanRankIcons._4);
//       add(SpriteID.ClanRankIcons._5);
//       add(SpriteID.ClanRankIcons._6);
//       add(SpriteID.ClanRankIcons._7);
//       add(SpriteID.ClanRankIcons._8);
//       add(SpriteID.ClanRankIcons._9);
//       add(SpriteID.ClanRankIcons._10);
//       add(SpriteID.ClanRankIcons._11);
//       add(SpriteID.ClanRankIcons._12);
//       add(SpriteID.ClanRankIcons._13);
//       add(SpriteID.ClanRankIcons._14);
//       add(SpriteID.ClanRankIcons._15);
//       add(SpriteID.ClanRankIcons._16);
//       add(SpriteID.ClanRankIcons._17);
//       add(SpriteID.ClanRankIcons._18);
//       add(SpriteID.ClanRankIcons._19);
//       add(SpriteID.ClanRankIcons._20);
//       add(SpriteID.ClanRankIcons._21);
//       add(SpriteID.ClanRankIcons._22);
//       add(SpriteID.ClanRankIcons._23);
//       add(SpriteID.ClanRankIcons._24);
//       add(SpriteID.ClanRankIcons._25);
//       add(SpriteID.ClanRankIcons._26);
//       add(SpriteID.ClanRankIcons._27);
//       add(SpriteID.ClanRankIcons._28);
//       add(SpriteID.ClanRankIcons._29);
//       add(SpriteID.ClanRankIcons._30);
//       add(SpriteID.ClanRankIcons._31);
//       add(SpriteID.ClanRankIcons._32);
//       add(SpriteID.ClanRankIcons._33);
//       add(SpriteID.ClanRankIcons._34);
//       add(SpriteID.ClanRankIcons._35);
//       add(SpriteID.ClanRankIcons._36);
//       add(SpriteID.ClanRankIcons._37);
//       add(SpriteID.ClanRankIcons._38);
//       add(SpriteID.ClanRankIcons._39);
//       add(SpriteID.ClanRankIcons._40);
//       add(SpriteID.ClanRankIcons._41);
//       add(SpriteID.ClanRankIcons._42);
//       add(SpriteID.ClanRankIcons._43);
//       add(SpriteID.ClanRankIcons._44);
//       add(SpriteID.ClanRankIcons._45);
//       add(SpriteID.ClanRankIcons._46);
//       add(SpriteID.ClanRankIcons._47);
//       add(SpriteID.ClanRankIcons._48);

//       add(SpriteID.Mapfunction._0);
//       add(SpriteID.Mapfunction._1);
//       add(SpriteID.Mapfunction._2);
//       add(SpriteID.Mapfunction._3);
//       add(SpriteID.Mapfunction._4);
//       add(SpriteID.Mapfunction._5);
//       add(SpriteID.Mapfunction._6);
//       add(SpriteID.Mapfunction._7);
//       add(SpriteID.Mapfunction._8);
//       add(SpriteID.Mapfunction._9);
//       add(SpriteID.Mapfunction._10);
//       add(SpriteID.Mapfunction._11);
//       add(SpriteID.Mapfunction._12);
//       add(SpriteID.Mapfunction._13);
//       add(SpriteID.Mapfunction._14);
//       add(SpriteID.Mapfunction._15);
//       add(SpriteID.Mapfunction._16);
//       add(SpriteID.Mapfunction._17);
//       add(SpriteID.Mapfunction._18);
//       add(SpriteID.Mapfunction._19);
//       add(SpriteID.Mapfunction._20);
//       add(SpriteID.Mapfunction._21);
//       add(SpriteID.Mapfunction._22);
//       add(SpriteID.Mapfunction._23);
//       add(SpriteID.Mapfunction._24);
//       add(SpriteID.Mapfunction._25);
//       add(SpriteID.Mapfunction._26);
//       add(SpriteID.Mapfunction._27);
//       add(SpriteID.Mapfunction._28);
//       add(SpriteID.Mapfunction._29);
//       add(SpriteID.Mapfunction._30);
//       add(SpriteID.Mapfunction._31);
//       add(SpriteID.Mapfunction._32);
//       add(SpriteID.Mapfunction._33);
//       add(SpriteID.Mapfunction._34);
//       add(SpriteID.Mapfunction._35);
//       add(SpriteID.Mapfunction._36);
//       add(SpriteID.Mapfunction._37);
//       add(SpriteID.Mapfunction._38);
//       add(SpriteID.Mapfunction._39);
//       add(SpriteID.Mapfunction._40);
//       add(SpriteID.Mapfunction._41);
//       add(SpriteID.Mapfunction._42);
//       add(SpriteID.Mapfunction._43);
//       add(SpriteID.Mapfunction._44);
//       add(SpriteID.Mapfunction._45);
//       add(SpriteID.Mapfunction._46);
//       add(SpriteID.Mapfunction._47);
//       add(SpriteID.Mapfunction._48);

//       add(SpriteID.Spectator.HITPOINTS);
//       add(SpriteID.Spectator.PRAYER);
//       add(SpriteID.Spectator.SPECIAL);

//       add(SpriteID.GodWarsIcons._0);
//       add(SpriteID.GodWarsIcons._1);
//       add(SpriteID.GodWarsIcons._2);
//       add(SpriteID.GodWarsIcons._3);
//       add(SpriteID.GodWarsIcons._4);

//       add(SpriteID.OsmStatusIcons._0);
//       add(SpriteID.OsmStatusIcons._1);
//       add(SpriteID.OsmStatusIcons._2);
//       add(SpriteID.OsmStatusIcons._3);
//       add(SpriteID.OsmStatusIcons._4);
//       add(SpriteID.OsmStatusIcons._5);
//       add(SpriteID.OsmStatusIcons._6);
//       add(SpriteID.OsmStatusIcons._7);

//       add(SpriteID.CaTierSwordsSmall._0);
//       add(SpriteID.CaTierSwordsSmall._1);
//       add(SpriteID.CaTierSwordsSmall._2);
//       add(SpriteID.CaTierSwordsSmall._3);
//       add(SpriteID.CaTierSwordsSmall._4);
//       add(SpriteID.CaTierSwordsSmall._5);

//       add(SpriteID.PvpwIcons.PLAYER_KILLER_SKULL);
//       add(SpriteID.PvpwIcons.PLAYER_KILLING_DISABLED_OVERLAY);
//       add(SpriteID.PvpwIcons.DEADMAN_EXCLAMATION_MARK_SKULLED_WARNING);

//       add(SpriteID.PvpaRankicons._0);
//       add(SpriteID.PvpaRankicons._1);
//       add(SpriteID.PvpaRankicons._2);
//       add(SpriteID.PvpaRankicons._3);
//       add(SpriteID.PvpaRankicons._4);
//       add(SpriteID.PvpaRankicons._5);
//       add(SpriteID.PvpaRankicons._6);
//       add(SpriteID.PvpaRankicons._7);

//       add(SpriteID.DeadmanSigilIcons._0);
//       add(SpriteID.DeadmanSigilIcons._1);
//       add(SpriteID.DeadmanSigilIcons._2);
//       add(SpriteID.DeadmanSigilIcons._3);
//       add(SpriteID.DeadmanSigilIcons._4);
//       add(SpriteID.DeadmanSigilIcons._5);
//       add(SpriteID.DeadmanSigilIcons._6);
//       add(SpriteID.DeadmanSigilIcons._7);
//       add(SpriteID.DeadmanSigilIcons._8);
//       add(SpriteID.DeadmanSigilIcons._9);
//       add(SpriteID.DeadmanSigilIcons._10);
//       add(SpriteID.DeadmanSigilIcons._11);
//       add(SpriteID.DeadmanSigilIcons._12);
//       add(SpriteID.DeadmanSigilIcons._13);
//       add(SpriteID.DeadmanSigilIcons._14);
//       add(SpriteID.DeadmanSigilIcons._15);
//       add(SpriteID.DeadmanSigilIcons._16);
//       add(SpriteID.DeadmanSigilIcons._17);
//       add(SpriteID.DeadmanSigilIcons._18);
//       add(SpriteID.DeadmanSigilIcons._19);
//       add(SpriteID.DeadmanSigilIcons._20);
//       add(SpriteID.DeadmanSigilIcons._21);
//       add(SpriteID.DeadmanSigilIcons._22);
//       add(SpriteID.DeadmanSigilIcons._23);
//       add(SpriteID.DeadmanSigilIcons._24);
//       add(SpriteID.DeadmanSigilIcons._25);
//       add(SpriteID.DeadmanSigilIcons._26);
//       add(SpriteID.DeadmanSigilIcons._27);
//       add(SpriteID.DeadmanSigilIcons._28);
//       add(SpriteID.DeadmanSigilIcons._29);
//       add(SpriteID.DeadmanSigilIcons._30);
//       add(SpriteID.DeadmanSigilIcons._31);
//       add(SpriteID.DeadmanSigilIcons._32);
//       add(SpriteID.DeadmanSigilIcons._33);
//       add(SpriteID.DeadmanSigilIcons._34);
//       add(SpriteID.DeadmanSigilIcons._35);
//       add(SpriteID.DeadmanSigilIcons._36);
//       add(SpriteID.DeadmanSigilIcons._37);
//       add(SpriteID.DeadmanSigilIcons._38);
//       add(SpriteID.DeadmanSigilIcons._39);
//       add(SpriteID.DeadmanSigilIcons._40);
//       add(SpriteID.DeadmanSigilIcons._41);
//       add(SpriteID.DeadmanSigilIcons._42);
//       add(SpriteID.DeadmanSigilIcons._43);
//       add(SpriteID.DeadmanSigilIcons._44);
//       add(SpriteID.DeadmanSigilIcons._45);
//       add(SpriteID.DeadmanSigilIcons._46);

//       add(SpriteID.DeadmanSigilSkulls._0);
//       add(SpriteID.DeadmanSigilSkulls._1);
//       add(SpriteID.DeadmanSigilSkulls._2);
//       add(SpriteID.DeadmanSigilSkulls._3);
//       add(SpriteID.DeadmanSigilSkulls._4);
//       add(SpriteID.DeadmanSigilSkulls._5);
//       add(SpriteID.DeadmanSigilSkulls._6);
//       add(SpriteID.DeadmanSigilSkulls._7);
//       add(SpriteID.DeadmanSigilSkulls._8);

//       add(SpriteID.DeadmanSigilCombatIconsSmall._0);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._1);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._2);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._3);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._4);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._5);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._6);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._7);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._8);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._9);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._10);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._11);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._12);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._13);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._14);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._15);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._16);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._17);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._18);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._19);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._20);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._21);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._22);
//       add(SpriteID.DeadmanSigilCombatIconsSmall._23);

//       add(SpriteID.DeadmanSigilSkillingIconsSmall._0);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._1);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._2);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._3);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._4);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._5);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._6);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._7);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._8);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._9);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._10);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._11);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._12);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._13);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._14);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._15);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._16);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._17);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._18);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._19);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._20);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._21);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._22);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._23);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._24);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._25);
//       add(SpriteID.DeadmanSigilSkillingIconsSmall._26);

//       add(SpriteID.DeadmanSigilUtilityIconsSmall._0);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._1);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._2);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._3);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._4);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._5);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._6);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._7);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._8);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._9);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._10);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._11);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._12);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._13);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._14);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._15);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._16);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._17);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._18);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._19);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._20);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._21);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._22);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._23);
//       add(SpriteID.DeadmanSigilUtilityIconsSmall._24);

//       add(SpriteID.LeagueTaskTiers._0);
//       add(SpriteID.LeagueTaskTiers._1);
//       add(SpriteID.LeagueTaskTiers._2);
//       add(SpriteID.LeagueTaskTiers._3);
//       add(SpriteID.LeagueTaskTiers._4);
//       add(SpriteID.LeagueTaskTiers._5);

//       add(SpriteID.LeagueTinyRelic._0);
//       add(SpriteID.LeagueTinyRelic._1);
//       add(SpriteID.LeagueTinyRelic._2);
//       add(SpriteID.LeagueTinyRelic._3);
//       add(SpriteID.LeagueTinyRelic._4);

//       add(SpriteID.LeagueRelics._0);
//       add(SpriteID.LeagueRelics._1);
//       add(SpriteID.LeagueRelics._2);
//       add(SpriteID.LeagueRelics._3);
//       add(SpriteID.LeagueRelics._4);
//       add(SpriteID.LeagueRelics._5);
//       add(SpriteID.LeagueRelics._6);
//       add(SpriteID.LeagueRelics._7);
//       add(SpriteID.LeagueRelics._8);
//       add(SpriteID.LeagueRelics._9);
//       add(SpriteID.LeagueRelics._10);
//       add(SpriteID.LeagueRelics._11);
//       add(SpriteID.LeagueRelics._12);
//       add(SpriteID.LeagueRelics._13);
//       add(SpriteID.LeagueRelics._14);
//       add(SpriteID.LeagueRelics._15);
//       add(SpriteID.LeagueRelics._16);
//       add(SpriteID.LeagueRelics._17);
//       add(SpriteID.LeagueRelics._18);
//       add(SpriteID.LeagueRelics._19);
//       add(SpriteID.LeagueRelics._20);
//       add(SpriteID.LeagueRelics._21);
//       add(SpriteID.LeagueRelics._22);
//       add(SpriteID.LeagueRelics._23);
//       add(SpriteID.LeagueRelics._24);
//       add(SpriteID.LeagueRelics._25);
//       add(SpriteID.LeagueRelics._26);
//       add(SpriteID.LeagueRelics._27);
//       add(SpriteID.LeagueRelics._28);
//       add(SpriteID.LeagueRelics._29);
//       add(SpriteID.LeagueRelics._30);
//       add(SpriteID.LeagueRelics._31);
//       add(SpriteID.LeagueRelics._32);
//       add(SpriteID.LeagueRelics._33);
//       add(SpriteID.LeagueRelics._34);
//       add(SpriteID.LeagueRelics._35);

//       add(SpriteID.TrailblazerRelics._0);
//       add(SpriteID.TrailblazerRelics._1);
//       add(SpriteID.TrailblazerRelics._2);
//       add(SpriteID.TrailblazerRelics._3);
//       add(SpriteID.TrailblazerRelics._4);
//       add(SpriteID.TrailblazerRelics._5);
//       add(SpriteID.TrailblazerRelics._6);
//       add(SpriteID.TrailblazerRelics._7);
//       add(SpriteID.TrailblazerRelics._8);
//       add(SpriteID.TrailblazerRelics._9);
//       add(SpriteID.TrailblazerRelics._10);
//       add(SpriteID.TrailblazerRelics._11);
//       add(SpriteID.TrailblazerRelics._12);
//       add(SpriteID.TrailblazerRelics._13);
//       add(SpriteID.TrailblazerRelics._14);
//       add(SpriteID.TrailblazerRelics._15);
//       add(SpriteID.TrailblazerRelics._16);
//       add(SpriteID.TrailblazerRelics._17);
//       add(SpriteID.TrailblazerRelics._18);
//       add(SpriteID.TrailblazerRelics._19);
//       add(SpriteID.TrailblazerRelics._20);
//       add(SpriteID.TrailblazerRelics._21);
//       add(SpriteID.TrailblazerRelics._22);
//       add(SpriteID.TrailblazerRelics._23);
//       add(SpriteID.TrailblazerRelics._24);
//       add(SpriteID.TrailblazerRelics._25);
//       add(SpriteID.TrailblazerRelics._26);
//       add(SpriteID.TrailblazerRelics._27);
//       add(SpriteID.TrailblazerRelics._28);
//       add(SpriteID.TrailblazerRelics._29);
//       add(SpriteID.TrailblazerRelics._30);
//       add(SpriteID.TrailblazerRelics._31);
//       add(SpriteID.TrailblazerRelics._32);
//       add(SpriteID.TrailblazerRelics._33);
//       add(SpriteID.TrailblazerRelics._34);
//       add(SpriteID.TrailblazerRelics._35);
//       add(SpriteID.TrailblazerRelics._36);
//       add(SpriteID.TrailblazerRelics._37);
//       add(SpriteID.TrailblazerRelics._38);
//       add(SpriteID.TrailblazerRelics._39);

//       add(SpriteID.TrailblazerMapShields._0);
//       add(SpriteID.TrailblazerMapShields._1);
//       add(SpriteID.TrailblazerMapShields._2);
//       add(SpriteID.TrailblazerMapShields._3);
//       add(SpriteID.TrailblazerMapShields._4);
//       add(SpriteID.TrailblazerMapShields._5);
//       add(SpriteID.TrailblazerMapShields._6);
//       add(SpriteID.TrailblazerMapShields._7);
//       add(SpriteID.TrailblazerMapShields._8);
//       add(SpriteID.TrailblazerMapShields._9);
//       add(SpriteID.TrailblazerMapShields._10);
//       add(SpriteID.TrailblazerMapShields._11);
//       add(SpriteID.TrailblazerMapShields._12);
//       add(SpriteID.TrailblazerMapShields._13);
//       add(SpriteID.TrailblazerMapShields._14);
//       add(SpriteID.TrailblazerMapShields._15);
//       add(SpriteID.TrailblazerMapShields._16);
//       add(SpriteID.TrailblazerMapShields._17);

//       add(SpriteID.League3Relics._0);
//       add(SpriteID.League3Relics._1);
//       add(SpriteID.League3Relics._2);
//       add(SpriteID.League3Relics._3);
//       add(SpriteID.League3Relics._4);
//       add(SpriteID.League3Relics._5);
//       add(SpriteID.League3Relics._6);
//       add(SpriteID.League3Relics._7);
//       add(SpriteID.League3Relics._8);
//       add(SpriteID.League3Relics._9);
//       add(SpriteID.League3Relics._10);
//       add(SpriteID.League3Relics._11);
//       add(SpriteID.League3Relics._12);
//       add(SpriteID.League3Relics._13);
//       add(SpriteID.League3Relics._14);
//       add(SpriteID.League3Relics._15);
//       add(SpriteID.League3Relics._16);
//       add(SpriteID.League3Relics._17);
//       add(SpriteID.League3Relics._18);
//       add(SpriteID.League3Relics._19);
//       add(SpriteID.League3Relics._20);
//       add(SpriteID.League3Relics._21);
//       add(SpriteID.League3Relics._22);
//       add(SpriteID.League3Relics._23);
//       add(SpriteID.League3Relics._24);
//       add(SpriteID.League3Relics._25);
//       add(SpriteID.League3Relics._26);
//       add(SpriteID.League3Relics._27);
//       add(SpriteID.League3Relics._28);
//       add(SpriteID.League3Relics._29);
//       add(SpriteID.League3Relics._30);
//       add(SpriteID.League3Relics._31);
//       add(SpriteID.League3Relics._32);
//       add(SpriteID.League3Relics._33);
//       add(SpriteID.League3Relics._34);
//       add(SpriteID.League3Relics._35);
//       add(SpriteID.League3Relics._36);
//       add(SpriteID.League3Relics._37);
//       add(SpriteID.League3Relics._38);
//       add(SpriteID.League3Relics._39);
//       add(SpriteID.League3Relics._40);
//       add(SpriteID.League3Relics._41);
//       add(SpriteID.League3Relics._42);
//       add(SpriteID.League3Relics._43);
//       add(SpriteID.League3Relics._44);
//       add(SpriteID.League3Relics._45);
//       add(SpriteID.League3Relics._46);
//       add(SpriteID.League3Relics._47);

//       add(SpriteID.League4Relics._0);
//       add(SpriteID.League4Relics._1);
//       add(SpriteID.League4Relics._2);
//       add(SpriteID.League4Relics._3);
//       add(SpriteID.League4Relics._4);
//       add(SpriteID.League4Relics._5);
//       add(SpriteID.League4Relics._6);
//       add(SpriteID.League4Relics._7);
//       add(SpriteID.League4Relics._8);
//       add(SpriteID.League4Relics._9);
//       add(SpriteID.League4Relics._10);
//       add(SpriteID.League4Relics._11);
//       add(SpriteID.League4Relics._12);
//       add(SpriteID.League4Relics._13);
//       add(SpriteID.League4Relics._14);
//       add(SpriteID.League4Relics._15);
//       add(SpriteID.League4Relics._16);
//       add(SpriteID.League4Relics._17);
//       add(SpriteID.League4Relics._18);
//       add(SpriteID.League4Relics._19);
//       add(SpriteID.League4Relics._20);
//       add(SpriteID.League4Relics._21);
//       add(SpriteID.League4Relics._26);

//       add(SpriteID.League4MapShields01._0);
//       add(SpriteID.League4MapShields01._1);
//       add(SpriteID.League4MapShields01._2);
//       add(SpriteID.League4MapShields01._3);
//       add(SpriteID.League4MapShields01._4);
//       add(SpriteID.League4MapShields01._5);
//       add(SpriteID.League4MapShields01._6);
//       add(SpriteID.League4MapShields01._7);
//       add(SpriteID.League4MapShields01._8);
//       add(SpriteID.League4MapShields01._9);
//       add(SpriteID.League4MapShields01._10);
//       add(SpriteID.League4MapShields01._11);
//       add(SpriteID.League4MapShields01._12);
//       add(SpriteID.League4MapShields01._13);
//       add(SpriteID.League4MapShields01._14);
//       add(SpriteID.League4MapShields01._15);
//       add(SpriteID.League4MapShields01._16);
//       add(SpriteID.League4MapShields01._17);
//       add(SpriteID.League4MapShields01._18);
//       add(SpriteID.League4MapShields01._19);

//       add(SpriteID.League5Relics._0);
//       add(SpriteID.League5Relics._1);
//       add(SpriteID.League5Relics._2);
//       add(SpriteID.League5Relics._3);
//       add(SpriteID.League5Relics._4);
//       add(SpriteID.League5Relics._5);
//       add(SpriteID.League5Relics._6);
//       add(SpriteID.League5Relics._7);
//       add(SpriteID.League5Relics._8);
//       add(SpriteID.League5Relics._9);
//       add(SpriteID.League5Relics._10);
//       add(SpriteID.League5Relics._11);
//       add(SpriteID.League5Relics._12);
//       add(SpriteID.League5Relics._13);
//       add(SpriteID.League5Relics._14);
//       add(SpriteID.League5Relics._15);
//       add(SpriteID.League5Relics._16);
//       add(SpriteID.League5Relics._17);
//       add(SpriteID.League5Relics._18);
//       add(SpriteID.League5Relics._19);
//       add(SpriteID.League5Relics._20);
//       add(SpriteID.League5Relics._21);
//       add(SpriteID.League5Relics._22);
//       add(SpriteID.League5Relics._26);

//       add(SpriteID.League5MapShields01._0);
//       add(SpriteID.League5MapShields01._1);
//       add(SpriteID.League5MapShields01._2);
//       add(SpriteID.League5MapShields01._3);
//       add(SpriteID.League5MapShields01._4);
//       add(SpriteID.League5MapShields01._5);
//       add(SpriteID.League5MapShields01._6);
//       add(SpriteID.League5MapShields01._7);
//       add(SpriteID.League5MapShields01._8);
//       add(SpriteID.League5MapShields01._9);
//       add(SpriteID.League5MapShields01._10);
//       add(SpriteID.League5MapShields01._11);
//       add(SpriteID.League5MapShields01._12);
//       add(SpriteID.League5MapShields01._13);
//       add(SpriteID.League5MapShields01._14);
//       add(SpriteID.League5MapShields01._15);
//       add(SpriteID.League5MapShields01._16);
//       add(SpriteID.League5MapShields01._17);
//       add(SpriteID.League5MapShields01._18);
//       add(SpriteID.League5MapShields01._19);
//       add(SpriteID.League5MapShields01._20);
//       add(SpriteID.League5MapShields01._21);
//       add(SpriteID.League5MapShields01._22);
//       add(SpriteID.League5MapShields01._23);

//       add(SpriteID.League5CombatMasterySmall._0);
//       add(SpriteID.League5CombatMasterySmall._1);
//       add(SpriteID.League5CombatMasterySmall._2);
//       add(SpriteID.League5CombatMasterySmall._3);
//       add(SpriteID.League5CombatMasterySmall._4);
//       add(SpriteID.League5CombatMasterySmall._5);
//       add(SpriteID.League5CombatMasterySmall._6);
//       add(SpriteID.League5CombatMasterySmall._7);
//       add(SpriteID.League5CombatMasterySmall._8);
//       add(SpriteID.League5CombatMasterySmall._9);
//       add(SpriteID.League5CombatMasterySmall._10);
//       add(SpriteID.League5CombatMasterySmall._11);
//       add(SpriteID.League5CombatMasterySmall._12);
//       add(SpriteID.League5CombatMasterySmall._13);
//       add(SpriteID.League5CombatMasterySmall._14);
//       add(SpriteID.League5CombatMasterySmall._15);
//       add(SpriteID.League5CombatMasterySmall._16);
//       add(SpriteID.League5CombatMasterySmall._17);

//       add(SpriteID.League5CombatMasteryTierSmall._0);
//       add(SpriteID.League5CombatMasteryTierSmall._1);
//       add(SpriteID.League5CombatMasteryTierSmall._2);
//       add(SpriteID.League5CombatMasteryTierSmall._3);
//       add(SpriteID.League5CombatMasteryTierSmall._4);
//       add(SpriteID.League5CombatMasteryTierSmall._5);

//       add(SpriteID.LeagueTrophyIcons._0);
//       add(SpriteID.LeagueTrophyIcons._1);
//       add(SpriteID.LeagueTrophyIcons._2);
//       add(SpriteID.LeagueTrophyIcons._3);
//       add(SpriteID.LeagueTrophyIcons._4);
//       add(SpriteID.LeagueTrophyIcons._5);
//       add(SpriteID.LeagueTrophyIcons._6);
//       add(SpriteID.LeagueTrophyIcons._7);

//       add(SpriteID.RomanNumerals._0);
//       add(SpriteID.RomanNumerals._1);
//       add(SpriteID.RomanNumerals._2);
//       add(SpriteID.RomanNumerals._3);

//       add(SpriteID.League3Numerals._0);
//       add(SpriteID.League3Numerals._1);
//       add(SpriteID.League3Numerals._2);
//       add(SpriteID.League3Numerals._3);
//       add(SpriteID.League3Numerals._4);
//       add(SpriteID.League3Numerals._5);
//       add(SpriteID.League3Numerals._6);
//       add(SpriteID.League3Numerals._7);
//       add(SpriteID.League3Numerals._8);
//       add(SpriteID.League3Numerals._9);
//       add(SpriteID.League3Numerals._10);
//       add(SpriteID.League3Numerals._11);
//       add(SpriteID.League3Numerals._12);
//       add(SpriteID.League3Numerals._13);

//     }
//   }.stream().distinct().collect(Collectors.toList());
// }
