package com.github.dappermickie.runepouch.loadout.names;

import net.runelite.api.gameval.SpriteID;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class RunepouchLoadoutIcon {
  public int spriteId;
  public String name;

  public RunepouchLoadoutIcon(int spriteId, String name) {
    this.spriteId = spriteId;
    this.name = name;
  }

  public static List<RunepouchLoadoutIcon> getIcons(String search) {
    if (search.isEmpty()) {
      return ICONS;
    }

    return ICONS.stream()
      .filter(icon -> icon.name.toLowerCase().contains(search.toLowerCase()))
      .collect(Collectors.toList());
  }

  public static final List<RunepouchLoadoutIcon> ICONS = new ArrayList<RunepouchLoadoutIcon>() {
    {
      add(new RunepouchLoadoutIcon(SpriteID.AccManIcons._6, "Default"));

      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WIND_STRIKE, "Wind Strike"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WATER_STRIKE, "Water Strike"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.EARTH_STRIKE, "Earth Strike"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.FIRE_STRIKE, "Fire Strike"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WIND_BOLT, "Wind Bolt"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WATER_BOLT, "Water Bolt"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.EARTH_BOLT, "Earth Bolt"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.FIRE_BOLT, "Fire Bolt"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WIND_BLAST, "Wind Blast"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WATER_BLAST, "Water Blast"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.EARTH_BLAST, "Earth Blast"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.FIRE_BLAST, "Fire Blast"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WIND_WAVE, "Wind Wave"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WATER_WAVE, "Water Wave"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.EARTH_WAVE, "Earth Wave"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.FIRE_WAVE, "Fire Wave"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.WIND_SURGE, "Wind Surge"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.WATER_SURGE, "Water Surge"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.EARTH_SURGE, "Earth Surge"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.FIRE_SURGE, "Fire Surge"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.IBAN_BLAST, "Iban Blast"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.CHARGE, "Charge"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.FLAMES_OF_ZAMORAK, "Flames of Zamorak"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CLAWS_OF_GUTHIX, "Claws of Guthix"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.SARADOMIN_STRIKE, "Saradomin Strike"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CRUMBLE_UNDEAD, "Crumble Undead"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.BIND, "Bind"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SNARE, "Snare"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.ENTANGLE, "Entangle"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.LUMBRIDGE_TELEPORT, "Lumbridge Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.FALADOR_TELEPORT, "Falador Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.VARROCK_TELEPORT, "Varrock Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CAMELOT_TELEPORT, "Camelot Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.ARDOUGNE_TELEPORT, "Ardougne Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WATCHTOWER_TELEPORT, "Watchtower Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TROLLHEIM_TELEPORT, "Trollheim Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_HOUSE, "Teleport to House"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.LUMBRIDGE_HOME_TELEPORT, "Lumbridge Home Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_APE_ATOLL, "Teleport to Ape Atoll"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_KOUREND, "Teleport to Kourend"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.CIVITAS_ILLA_FORTIS_TELEPORT, "Civitas Ila Fortis Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELE_BLOCK, "Tele Block"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.TELEKINETIC_GRAB, "Telekinetic Grab"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEOTHER_LUMBRIDGE, "Teleother Lumbridge"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEOTHER_FALADOR, "Teleother Falador"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEOTHER_CAMELOT, "Teleother Camelot"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_BOUNTY_TARGET, "Teleport to Bounty Target"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CONFUSE, "Confuse"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.WEAKEN, "Weaken"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CURSE, "Curse"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.ENFEEBLE, "Enfeeble"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.STUN, "Stun"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.VULNERABILITY, "Vulnerability"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.LOW_LEVEL_ALCHEMY, "Low Level Alchemy"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.HIGH_LEVEL_ALCHEMY, "High Level Alchemy"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.SUPERHEAT_ITEM, "Superheat Item"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_1_ENCHANT, "Lvl 1 Enchant"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_2_ENCHANT, "Lvl 2 Enchant"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_3_ENCHANT, "Lvl 3 Enchant"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_4_ENCHANT, "Lvl 4 Enchant"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_5_ENCHANT, "Lvl 5 Enchant"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.LVL_6_ENCHANT, "Lvl 6 Enchant"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.LVL_7_ENCHANT, "Lvl 7 Enchant"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.ENCHANT_CROSSBOW_BOLT, "Enchant Crossbow Bolt"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CHARGE_WATER_ORB, "Charge Water Orb"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CHARGE_EARTH_ORB, "Charge Earth Orb"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CHARGE_FIRE_ORB, "Charge Fire Orb"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CHARGE_AIR_ORB, "Charge Air Orb"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.BONES_TO_BANANAS, "Bones to Bananas"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.BONES_TO_PEACHES, "Bones to Peaches"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.MAGIC_DART, "Magic Dart"));

      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.ICE_RUSH, "Ice Rush"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.ICE_BURST, "Ice Burst"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.ICE_BLITZ, "Ice Blitz"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.ICE_BARRAGE, "Ice Barrage"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SMOKE_RUSH, "Smoke Rush"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SMOKE_BURST, "Smoke Burst"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SMOKE_BLITZ, "Smoke Blitz"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SMOKE_BARRAGE, "Smoke Barrage"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.BLOOD_RUSH, "Blood Rush"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.BLOOD_BURST, "Blood Burst"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.BLOOD_BLITZ, "Blood Blitz"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.BLOOD_BARRAGE, "Blood Barrage"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SHADOW_RUSH, "Shadow Rush"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SHADOW_BURST, "Shadow Burst"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SHADOW_BLITZ, "Shadow Blitz"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SHADOW_BARRAGE, "Shadow Barrage"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.PADDEWWA_TELEPORT, "Paddewwa Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.SENNTISTEN_TELEPORT, "Senntisten Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.KHARYRLL_TELEPORT, "Kharyll Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.LASSAR_TELEPORT, "Lassar Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.DAREEYAK_TELEPORT, "Dareeyak Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.CARRALLANGAR_TELEPORT, "Carrallangar Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.ANNAKARL_TELEPORT, "Annakarl Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon2.GHORROCK_TELEPORT, "Ghorrock Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.CALL_ANIMAL, "Call Animal"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.RAISE_SKELETON, "Raise Skeleton"));
      add(new RunepouchLoadoutIcon(SpriteID.Magicon.SUMMON_DEMON, "Summon Demon"));

      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.BAKE_PIE, "Bake Pie"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.SUPERGLASS_MAKE, "Superglass Make"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.STRING_JEWELLERY, "String Jewellery"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.RECHARGE_DRAGONSTONE, "Recharge Dragonstone"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TAN_LEATHER, "Tan Leather"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.SPIN_FLAX, "Spin Flax"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.PLANK_MAKE, "Plank Make"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.MAGIC_IMBUE, "Magic Imbue"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.FERTILE_SOIL, "Fertile Soil"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_PLANT, "Cure Plant"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.GEOMANCY, "Geomancy"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.HUMIDIFY, "Humidify"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.BOW_AND_ARROW, "Bow and Arrow"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.NPC_CONTACT, "NPC Contact"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.BOOST_POTION_SHARE, "Boost Potion Share"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.STAT_RESTORE_POT_SHARE, "Stat Restore Pot Share"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.ENERGY_TRANSFER, "Energy Transfer"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.VENGEANCE, "Vengeance"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.VENGEANCE_OTHER, "Vengeance Other"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_ME, "Cure Me"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_GROUP, "Cure Group"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_OTHER, "Cure Other"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.HEAL_GROUP, "Heal Group"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.HEAL_OTHER, "Heal Other"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.MOONCLAN_TELEPORT, "Moonclan Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.WATERBIRTH_TELEPORT, "Waterbirth Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.BARBARIAN_TELEPORT, "Barbarian Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.KHAZARD_TELEPORT, "Khazard Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.FISHING_GUILD_TELEPORT, "Fishing Guild Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CATHERBY_TELEPORT, "Catherby Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.ICE_PLATEAU_TELEPORT, "Ice Plateau Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_MOONCLAN, "Tele Group Moonclan"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_WATERBIRTH, "Tele Group Waterbirth"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_BARBARIAN, "Tele Group Barbarian"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_KHAZARD, "Tele Group Khazard"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_FISHING_GUILD, "Tele Group Fishing Guild"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_CATHERBY, "Tele Group Catherby"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_ICE_PLATEAU, "Tele Group Ice Plateau"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.OURANIA_TELEPORT, "Ourania Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.STAT_SPY, "Stat Spy"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.MONSTER_EXAMINE, "Monster Examine"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.HUNTER_KIT, "Hunter Kit"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.DREAM, "Dream"));
      add(new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.SPELLBOOK_SWAP, "Spellbook Swap"));

      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_LESSER_GHOST, "Resurrect Lesser Ghost"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._24, "Resurrect Lesser Skeleton"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._25, "Resurrect Lesser Zombie"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._44, "Resurrect Superior Ghost (_44)"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_SUPERIOR_SKELETON, "Resurrect Superior Skeleton"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._48, "Resurrect Superior Zombie (_48)"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._45, "Resurrect Greater Ghost (_45)"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._47, "Resurrect Greater Skeleton (_47)"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_GREATER_ZOMBIE, "Resurrect Greater Zombie"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.ADEPT_REANIMATION, "Adept Reanimation"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.BASIC_REANIMATION, "Basic Reanimation"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.EXPERT_REANIMATION, "Expert Reanimation"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.MASTER_REANIMATION, "Master Reanimation"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.ARCEUUS_LIBRARY_TELEPORT, "Arceuus Library Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DRAYNOR_MANOR_TELEPORT, "Draynor Manor Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SALVE_GRAVEYARD_TELEPORT, "Salve Graveyard Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.MIND_ALTAR_TELEPORT, "Mind Altar Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESPAWN_TELEPORT, "Respawn Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.FENKENSTRAINS_CASTLE_TELEPORT, "Fenkenstrain's Castle Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.WEST_ARDOUGNE_TELEPORT, "West Ardougne Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.HARMONY_ISLAND_TELEPORT, "Harmony Island Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.BARROWS_TELEPORT, "Barrows Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.APE_ATOLL_TELEPORT, "Ape Atoll Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.CEMETERY_TELEPORT, "Cemetery Teleport"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_CROPS, "Resurrect Crops"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.GHOSTLY_GRASP, "Ghostly Grasp"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SKELETAL_GRASP, "Skeletal Grasp"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.UNDEAD_GRASP, "Undead Grasp"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.INFERIOR_DEMONBANE, "Inferior Demonbane"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SUPERIOR_DEMONBANE, "Superior Demonbane"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DARK_DEMONBANE, "Dark Demonbane"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.MARK_OF_DARKNESS, "Mark of Darkness"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.WARD_OF_ARCEUUS, "Ward of Arceuus"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.LESSER_CORRUPTION, "Lesser Corruption"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.GREATER_CORRUPTION, "Greater Corruption"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DEATH_CHARGE, "Death Charge"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DEMONIC_OFFERING, "Demonic Offering"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SINISTER_OFFERING, "Sinister Offering"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SHADOW_VEIL, "Shadow Veil"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DARK_LURE, "Dark Lure"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.VILE_VIGOUR, "Vile Vigour"));
      add(new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DEGRIME, "Degrime"));
      
      add(new RunepouchLoadoutIcon(SpriteID.SideIcons.MAGIC, "Spellbook Standard"));
      add(new RunepouchLoadoutIcon(SpriteID.SideIcons.SPELLBOOK_ANCIENT_MAGICKS, "Spellbook Ancient"));
      add(new RunepouchLoadoutIcon(SpriteID.SideIcons.SPELLBOOK_LUNAR, "Spellbook Lunar"));
      add(new RunepouchLoadoutIcon(SpriteID.SideIcons.SPELLBOOK_ARCEUUS, "Spellbook Arceuus"));
      
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.THICK_SKIN, "Thick Skin"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.BURST_OF_STRENGTH, "Burst of Strength"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.CLARITY_OF_THOUGHT, "Clarity of Thought"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.ROCK_SKIN, "Rock Skin"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.SUPERHUMAN_STRENGTH, "Superhuman Strength"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.IMPROVED_REFLEXES, "Improved Reflexes"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.RAPID_RESTORE, "Rapid Restore"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.RAPID_HEAL, "Rapid Heal"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_ITEM, "Protect Item"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.STEEL_SKIN, "Steel Skin"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.ULTIMATE_STRENGTH, "Ultimate Strength"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.INCREDIBLE_REFLEXES, "Incredible Reflexes"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_MAGIC, "Protect From Magic"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_MISSILES, "Protect From Missiles"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_MELEE, "Protect From Melee"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.REDEMPTION, "Redemption"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.RETRIBUTION, "Retribution"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.SMITE, "Smite"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.SHARP_EYE, "Sharp Eye"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.MYSTIC_WILL, "Mystic Will"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.HAWK_EYE, "Hawk Eye"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.MYSTIC_LORE, "Mystic Lore"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.EAGLE_EYE, "Eagle Eye"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.MYSTIC_MIGHT, "Mystic Might"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_SUMMONING, "Protect From Summoning"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.CHIVALRY, "Chivalry"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.PIETY, "Piety"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.PRESERVE, "Preserve"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.RIGOUR, "Rigour"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.AUGURY, "Augury"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.DEADEYE, "Deadeye"));
      add(new RunepouchLoadoutIcon(SpriteID.Prayeron.MYSTIC_VIGOUR, "Mystic Vigour"));

      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANCIENT_STRENGTH, "Ancient Strength"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANCIENT_SIGHT, "Ancient Sight"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANCIENT_WILL, "Ancient Will"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.TRINITAS, "Trinitas"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.DECIMATE, "Decimate"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANNIHILATE, "Annihilate"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.VAPORISE, "Vaporise"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.DAMPEN_MELEE, "Dampen Melee"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.DAMPEN_RANGED, "Dampen Ranged"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.DAMPEN_MAGIC, "Dampen Magic"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.PURGE, "Purge"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.REJUVENATION, "Rejuvenation"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.RUINOUS_GRACE, "Ruinous Grace"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.WRATH, "Wrath"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.METABOLISE, "Metabolise"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.BERSERKER, "Berserker"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.FUMUS_VOW, "Fumus Vow"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.CRUORS_VOW, "Cruors Vow"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.UMBRAS_VOW, "Umbras Vow"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.GLACIES_VOW, "Glacies Vow"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.INTENSIFY, "Intensify"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.REBUKE, "Rebuke"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.VINDICATION, "Vindication"));
      add(new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.PROTECT_ITEM, "Protect Item"));

      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ABYSSAL_SIRE, "Abyssal Sire"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ALCHEMICAL_HYDRA, "Alchemical Hydra"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.AMOXLIATL, "Amoxliatl"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_HUEYCOATL, "The Hueycoatl"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ROYAL_TITANS, "Royal Titans"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.YAMA, "Yama"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DOOM_OF_MOKHAIOTL, "Doom of Mokhaiotl"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.MIMIC, "Mimic"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.OBOR, "Obor"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ARAXXOR, "Araxxor"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.BRYOPHYTA, "Bryophyta"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.GIANT_MOLE, "Giant Mole"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.GROTESQUE_GUARDIANS, "Grotesque Guardians"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TEMPOROSS, "Tempoross"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.WINTERTODT, "Wintertodt"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.BARROWS_CHESTS, "Barrows Chests"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SARACHNIS, "Sarachnis"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KALPHITE_QUEEN, "Kalphite Queen"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.HESPORI, "Hespori"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SKOTIZO, "Skotizo"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ZALCANO, "Zalcano"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KING_BLACK_DRAGON, "King Black Dragon"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KRAKEN, "Kraken"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THERMONUCLEAR_SMOKE_DEVIL, "Thermonuclear Smoke Devil"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_GAUNTLET, "The Gauntlet"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ZULRAH, "Zulrah"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CERBERUS, "Cerberus"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.VORKATH, "Vorkath"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.GENERAL_GRAARDOR, "General Graardor"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KRIL_TSUTSAROTH, "Kril Tsutsaroth"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.COMMANDER_ZILYANA, "Commander Zilyana"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KREEARRA, "Kree'arra"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.NIGHTMARE, "Nightmare"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CORPOREAL_BEAST, "Corporeal Beast"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CHAMBERS_OF_XERIC, "Chambers of Xeric"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THEATRE_OF_BLOOD, "Theatre of Blood"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.NEX, "Nex"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DAGANNOTH_SUPREME, "Dagannoth Supreme"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DAGANNOTH_REX, "Dagannoth Rex"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DAGANNOTH_PRIME, "Dagannoth Prime"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_CORRUPTED_GAUNTLET, "The Corrupted Gauntlet"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CHAMBERS_OF_XERIC_CHALLENGE_MODE, "Chambers of Xeric Challenge Mode"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TOMBS_OF_AMASCUT, "Tombs of Amascut"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TOMBS_OF_AMASCUT_EXPERT, "Tombs of Amascut Expert"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.PHANTOM_MUSPAH, "Phantom Muspah"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CHAOS_ELEMENTAL, "Chaos Elemental"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ARTIO_CALLISTO, "Artio Callisto"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CALVARION_VETION, "Calvarion Vetion"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SPINDEL_VENENATIS, "Spindel Venenatis"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CHAOS_FANATIC, "Chaos Fanatic"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CRAZY_ARCHAEOLOGIST, "Crazy Archaeologist"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DERANGED_ARCHAEOLOGIST, "Deranged Archaeologist"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SCORPIA, "Scorpia"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TZTOK_JAD, "TzTok Jad"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TZKAL_ZUK, "TzKal Zuk"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_WHISPERER, "The Whisperer"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DUKE_SUCELLUS, "Duke Sucellus"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_LEVIATHAN, "The Leviathan"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.VARDORVIS, "Vardorvis"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SCURRIUS, "Scurrius"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SOL_HEREDIT, "Sol Heri"));
      add(new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.LUNAR_CHESTS, "Lunar Chests"));

      add(new RunepouchLoadoutIcon(SpriteID.Staticons.ATTACK, "Attack"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.STRENGTH, "Strength"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.DEFENCE, "Defence"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.RANGED, "Ranged"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.PRAYER, "Prayer"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.MAGIC, "Magic"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.HITPOINTS, "Hitpoints"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.AGILITY, "Agility"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.HERBLORE, "Herblore"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.THIEVING, "Thieving"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.CRAFTING, "Crafting"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.FLETCHING, "Fletching"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.MINING, "Mining"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.SMITHING, "Smithing"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.FISHING, "Fishing"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.COOKING, "Cooking"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.FIREMAKING, "Firemaking"));
      add(new RunepouchLoadoutIcon(SpriteID.Staticons.WOODCUTTING, "Woodcutting"));

      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._0, "Clan Rank 0"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._1, "Clan Rank 1"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._2, "Clan Rank 2"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._3, "Clan Rank 3"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._4, "Clan Rank 4"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._5, "Clan Rank 5"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._6, "Clan Rank 6"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._7, "Clan Rank 7"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._8, "Clan Rank 8"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._9, "Clan Rank 9"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._10, "Clan Rank 10"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._11, "Clan Rank 11"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._12, "Clan Rank 12"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._13, "Clan Rank 13"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._14, "Clan Rank 14"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._15, "Clan Rank 15"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._16, "Clan Rank 16"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._17, "Clan Rank 17"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._18, "Clan Rank 18"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._19, "Clan Rank 19"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._20, "Clan Rank 20"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._21, "Clan Rank 21"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._22, "Clan Rank 22"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._23, "Clan Rank 23"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._24, "Clan Rank 24"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._25, "Clan Rank 25"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._26, "Clan Rank 26"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._27, "Clan Rank 27"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._28, "Clan Rank 28"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._29, "Clan Rank 29"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._30, "Clan Rank 30"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._31, "Clan Rank 31"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._32, "Clan Rank 32"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._33, "Clan Rank 33"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._34, "Clan Rank 34"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._35, "Clan Rank 35"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._36, "Clan Rank 36"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._37, "Clan Rank 37"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._38, "Clan Rank 38"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._39, "Clan Rank 39"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._40, "Clan Rank 40"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._41, "Clan Rank 41"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._42, "Clan Rank 42"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._43, "Clan Rank 43"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._44, "Clan Rank 44"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._45, "Clan Rank 45"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._46, "Clan Rank 46"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._47, "Clan Rank 47"));
      add(new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._48, "Clan Rank 48"));

      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._0, "PK Skull"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._1, "TzHaar Fight Pit Skull"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._2, "High Risk Skull"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._3, "Forinthry Surge Skull"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._7, "Loot Keys Skull 0"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._8, "Loot Keys Skull 1"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._9, "Loot Keys Skull 2"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._10, "Loot Keys Skull 3"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._11, "Loot Keys Skull 4"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._12, "Loot Keys Skull 5"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._14, "Forinthry Loot Keys Skull 0"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._15, "Forinthry Loot Keys Skull 1"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._16, "Forinthry Loot Keys Skull 2"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._17, "Forinthry Loot Keys Skull 3"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._18, "Forinthry Loot Keys Skull 4"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._19, "Forinthry Loot Keys Skull 5"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._21, "Bounty Hunter Risk 1"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._22, "Bounty Hunter Risk 2"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._23, "Bounty Hunter Risk 3"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._24, "Bounty Hunter Risk 4"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._25, "Bounty Hunter Risk 5"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._28, "Skulled Bounty Hunter Risk 1"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._29, "Skulled Bounty Hunter Risk 2"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._30, "Skulled Bounty Hunter Risk 3"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._31, "Skulled Bounty Hunter Risk 4"));
      add(new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._32, "Skulled Bounty Hunter Risk 5"));

      add(new RunepouchLoadoutIcon(SpriteID.CaTierSwords._0, "Combat Achievement Rank 1"));
      add(new RunepouchLoadoutIcon(SpriteID.CaTierSwordsSmall._1, "Combat Achievement Rank 2"));
      add(new RunepouchLoadoutIcon(SpriteID.CaTierSwordsSmall._2, "Combat Achievement Rank 3"));
      add(new RunepouchLoadoutIcon(SpriteID.CaTierSwordsSmall._3, "Combat Achievement Rank 4"));
      add(new RunepouchLoadoutIcon(SpriteID.CaTierSwordsSmall._4, "Combat Achievement Rank 5"));
      add(new RunepouchLoadoutIcon(SpriteID.CaTierSwordsSmall._5, "Combat Achievement Rank 6"));

      add(new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._0, "Rank Bronze"));
      add(new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._1, "Rank Iron"));
      add(new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._2, "Rank Steel"));
      add(new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._3, "Rank Mithril"));
      add(new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._4, "Rank Adamant"));
      add(new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._5, "Rank Rune"));
      add(new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._6, "Rank Dragon"));
      add(new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._7, "Rank Master"));
    }
  };
}

